# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class GitUiTool < Formula
  desc "A TUI to add & edit git hooks, edit the commit message, edit a custom git log."
  homepage "https://github.com/DavidPerezP124/homebrew-git-ui-tool"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/DavidPerezP124/git-tool/releases/download/v0.0.1/git-tool_0.0.1_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "1f9b18292b025af663ba07b2fa1a59304c39c2e58a3f71966aca161dfa978fd4"

      def install
        bin.install "git-tool"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DavidPerezP124/git-tool/releases/download/v0.0.1/git-tool_0.0.1_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "efd4ba3ae201062b8ab3c002d3e63fe71d2afeb1395f47de82ba83d90c6e2d9b"

      def install
        bin.install "git-tool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DavidPerezP124/git-tool/releases/download/v0.0.1/git-tool_0.0.1_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "ef602916d2f07f20135aee245eccf356c3eb8d07acef6d9446b67fff17ffb6bd"

      def install
        bin.install "git-tool"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DavidPerezP124/git-tool/releases/download/v0.0.1/git-tool_0.0.1_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "a792d7fc3a370d011f7004104ce738e91dad9f7626e3564f9a81d9b048f29608"

      def install
        bin.install "git-tool"
      end
    end
  end

  depends_on "git"
  depends_on "zsh"
end
