# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class GitUiTool < Formula
  desc "A TUI to add & edit git hooks, edit the commit message, edit a custom git log."
  homepage "https://github.com/DavidPerezP124/homebrew-git-ui-tool"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/DavidPerezP124/git-tool/releases/download/v0.0.1/git-tool_0.0.1_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "150ca72f87aaa0439e65c48f471d2ed7b3688593f052ddfbe90cc0c972eab9b7"

      def install
        bin.install "git-tool"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DavidPerezP124/git-tool/releases/download/v0.0.1/git-tool_0.0.1_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "24abbb7d5d48a693a33d1b5752c51002b09d000ab85423e6ac752400c0f0c723"

      def install
        bin.install "git-tool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DavidPerezP124/git-tool/releases/download/v0.0.1/git-tool_0.0.1_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "f28202109c89890ccf17e5eadad954d51ae1b91de382635304a734aa768d19f3"

      def install
        bin.install "git-tool"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DavidPerezP124/git-tool/releases/download/v0.0.1/git-tool_0.0.1_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "4632038d85a67d41a74e5a97f77ae5d7dc8da9829fd56ca8c49b4a9aafe31b20"

      def install
        bin.install "git-tool"
      end
    end
  end

  depends_on "git"
  depends_on "zsh"
end
