# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitUiTool < Formula
  desc "TUI for managing git hooks, git commit message and git log"
  homepage "https://github.com/DavidPerezP124/homebrew-git-ui-tool"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/DavidPerezP124/homebrew-git-ui-tool/releases/download/v0.0.4/homebrew-git-ui-tool_0.0.4_Darwin_arm64.tar.gz"
      sha256 "957ce83937aa9ce775f7bac07a5097f3817993b385b7b9c1a391ef143b6fee60"

      def install
        bin.install "git-ui-tool"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DavidPerezP124/homebrew-git-ui-tool/releases/download/v0.0.4/homebrew-git-ui-tool_0.0.4_Darwin_x86_64.tar.gz"
      sha256 "26bcfec83a84dc4b701536b08b602de509549e4e8452722028531e1ff1c9093f"

      def install
        bin.install "git-ui-tool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DavidPerezP124/homebrew-git-ui-tool/releases/download/v0.0.4/homebrew-git-ui-tool_0.0.4_Linux_arm64.tar.gz"
      sha256 "27fbecae81d7de4b7f968191ad5c584540c4361cf50c2962b2e6bd0e8e60c507"

      def install
        bin.install "git-ui-tool"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DavidPerezP124/homebrew-git-ui-tool/releases/download/v0.0.4/homebrew-git-ui-tool_0.0.4_Linux_x86_64.tar.gz"
      sha256 "a164d5c9489b843d9013f4177c46579d4dc1ccfb27333c9c4513810ceab13631"

      def install
        bin.install "git-ui-tool"
      end
    end
  end
end
