# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitUiTool < Formula
  desc ""
  homepage "https://github.com/DavidPerezP124/homebrew-git-ui-tool"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/DavidPerezP124/homebrew-git-ui-tool/releases/download/v0.0.1/homebrew-git-ui-tool_0.0.1_Darwin_arm64.tar.gz"
      sha256 "dfa6876297305556d13607092e7d37d981a353ce3398fe062a02c6b0ce491674"

      def install
        bin.install "homebrew-git-ui-tool"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DavidPerezP124/homebrew-git-ui-tool/releases/download/v0.0.1/homebrew-git-ui-tool_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "6926c31302ada150aa617611a2a6b1d38bbee94ef3407f23c3274fa057ab6d41"

      def install
        bin.install "homebrew-git-ui-tool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DavidPerezP124/homebrew-git-ui-tool/releases/download/v0.0.1/homebrew-git-ui-tool_0.0.1_Linux_arm64.tar.gz"
      sha256 "2deda710885593bce5bf06fd89dfa77b67af8346a954c4e449dbde01737aa04e"

      def install
        bin.install "homebrew-git-ui-tool"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DavidPerezP124/homebrew-git-ui-tool/releases/download/v0.0.1/homebrew-git-ui-tool_0.0.1_Linux_x86_64.tar.gz"
      sha256 "f01d1d017f76c767a8ef051a3e7ca61701010bd84f5b8ef915b05ff81b1c0928"

      def install
        bin.install "homebrew-git-ui-tool"
      end
    end
  end

  depends_on "git"
  depends_on "zsh" => :optional
end
